name: test-custom-actions

on: [push]

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Show runner info
        run: pwd; ls -la /home/runner/work/SalsaGate
      
      - name: test
        uses: actions/checkout@v4
      - name: Show runner info
        run: pwd; ls -la /home/runner/work/SalsaGate/SalsaGate

      - name: Run GoodBye World
        uses: .github/.actions/SalsaGate/goodbye_world










