name: test-generating provenance

on: [push]

jobs:
  
  test1:
    runs-on: ubuntu-latest
    permissions:
      id-token: write        # REQUIRED for OIDC token (attestation signing)
      contents: read
      actions: read
      attestations: write
    outputs:
      hashes: ${{ steps.generate_hash.outputs.hashes }}
    steps:
      - name: Show runner info
        run: pwd; ls -la /home/runner/work/SalsaGate
      
      - name: test
        uses: actions/checkout@v4

      - name: Show runner info
        run: pwd; ls -la /home/runner/work/SalsaGate/SalsaGate
      
      # Not required if we bundle and publish the puglin.
      - name: install plugin dependencies 
        run: npm ci
        working-directory: ./.github/.actions/SalsaGate/hello_world/

      - name: Run Hello World
        uses: ./.github/.actions/SalsaGate/hello_world/
      
      - name: Generate Hash
        id: generate_hash
        run: echo $(sha256sum hello_world.json | awk '{print $1}' | xxd -r -p | base64 -w0) >> $GITHUB_OUTPUT
      
      #- name: Attest
      #  uses: actions/attest-build-provenance@v3
      #  with:
      #    subject-path: /home/runner/work/SalsaGate/SalsaGate/hello_world.json

  provenance:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    with:
      base64-subjects: "${{ needs.test1.outputs.hashes }}"
      upload-assets: false
    


      
      


